#!/usr/bin/env sh

CUR_DIR=$(dirname "$(readlink -f "$0")")

! type mkarchiso >/dev/null 2>&1 && sudo pacman -S archiso

sudo rm -rf /tmp/archiso-tmp

sudo mkarchiso -v -w /tmp/archiso-tmp $CUR_DIR/base
