#!/usr/bin/env sh

WORKDIR=$(dirname "$(readlink -f "$0")")

rm -rf "$WORKDIR/out/*"
sudo rm -rf /tmp/archiso-tmp

! type mkarchiso >/dev/null 2>&1 && sudo pacman --noconfirm -S archiso

sudo mkarchiso -v -w /tmp/archiso-tmp $WORKDIR/base

if [ $? -ne 0 ]; then
	exit
fi

sudo ln -s $(find $WORKDIR/out/archlinux-20*.iso) $WORKDIR/out/archlinux.iso
